// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpliglvivfjbnemebqca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwbGlnbHZpdmZqYm5lbWVicWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MjQxOTMsImV4cCI6MjA1NDEwMDE5M30.81gVR-Up0BcQA1ieisIkibPmN5y6FKqqA3uV3XjWIzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);